services:
  mysqldb:
    image: mysql:8.4
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQLDB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    build: .
    image: movie-catalog-app
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    env_file: .env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"

volumes:
  mysql_data:
